apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cloud-deploy
deploy:
  kustomize:
    defaultNamespace: dev2
    paths: 
      - k8s/overlays/dev
profiles:
  - name: pre
    deploy:
      kustomize:
        defaultNamespace: pre2
        paths: 
          - k8s/overlays/pre
  - name: pro
    deploy:
      kustomize:
        defaultNamespace: pro2
        paths: 
          - k8s/overlays/pro