apiVersion: v1
kind: Service
metadata:
  name: treewebservice
  namespace: treeweb
spec:
  selector:
    app: treeweb
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000